16:46:20.525 [main] ERROR s.c.l.slf4j.Slf4jLoggingBackend - Exception when sending request: POST http://localhost/8080/query, took: 0.039s
sttp.client4.SttpClientException$ConnectException: Exception when sending request: POST http://localhost/8080/query
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:12)
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:8)
	at sttp.client4.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions$$anonfun$1(HttpClientBackend.scala:56)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at sttp.monad.MonadError.handleError(MonadError.scala:28)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.SttpClientException$.adjustExceptions(SttpClientException.scala:35)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions(HttpClientBackend.scala:56)
	at sttp.client4.httpclient.HttpClientBackend.send(HttpClientBackend.scala:48)
	at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
	at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1$$anonfun$1(ListenerBackend.scala:18)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1(ListenerBackend.scala:19)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2(ListenerBackend.scala:21)
	at sttp.monad.IdentityMonad$.flatMap(MonadError.scala:178)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send(ListenerBackend.scala:22)
	at sttp.client4.Request.send(request.scala:159)
	at org.CS441.hw3.hdongr2.RestClient$.generate(RestClient.scala:29)
	at org.CS441.hw3.hdongr2.RestClient$.clientLoop(RestClient.scala:39)
	at org.CS441.hw3.hdongr2.RestClient$.runClientLoop(RestClient.scala:47)
	at org.CS441.hw3.hdongr2.runClientLoop.main(RestClient.scala:44)
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:40)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:38)
	at sttp.client4.httpclient.HttpClientBackend.send$$anonfun$1(HttpClientBackend.scala:47)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	... 23 common frames omitted
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1082)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:978)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:955)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:204)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:958)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
	... 9 common frames omitted
16:47:27.558 [main] ERROR s.c.l.slf4j.Slf4jLoggingBackend - Exception when sending request: POST http://localhost/8080/query, took: 0.032s
sttp.client4.SttpClientException$ConnectException: Exception when sending request: POST http://localhost/8080/query
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:12)
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:8)
	at sttp.client4.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions$$anonfun$1(HttpClientBackend.scala:56)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at sttp.monad.MonadError.handleError(MonadError.scala:28)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.SttpClientException$.adjustExceptions(SttpClientException.scala:35)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions(HttpClientBackend.scala:56)
	at sttp.client4.httpclient.HttpClientBackend.send(HttpClientBackend.scala:48)
	at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
	at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1$$anonfun$1(ListenerBackend.scala:18)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1(ListenerBackend.scala:19)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2(ListenerBackend.scala:21)
	at sttp.monad.IdentityMonad$.flatMap(MonadError.scala:178)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send(ListenerBackend.scala:22)
	at sttp.client4.Request.send(request.scala:159)
	at org.CS441.hw3.hdongr2.RestClient$.generate(RestClient.scala:30)
	at org.CS441.hw3.hdongr2.RestClient$.clientLoop(RestClient.scala:42)
	at org.CS441.hw3.hdongr2.RestClient$.runClientLoop(RestClient.scala:50)
	at org.CS441.hw3.hdongr2.runClientLoop.main(RestClient.scala:47)
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:40)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:38)
	at sttp.client4.httpclient.HttpClientBackend.send$$anonfun$1(HttpClientBackend.scala:47)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	... 23 common frames omitted
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1082)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:978)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:955)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1817)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:204)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:958)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
	... 9 common frames omitted
16:48:59.182 [sbt-bg-threads-1] ERROR s.c.l.slf4j.Slf4jLoggingBackend - Exception when sending request: POST http://localhost/8080/query, took: 0.043s
sttp.client4.SttpClientException$ConnectException: Exception when sending request: POST http://localhost/8080/query
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:12)
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:8)
	at sttp.client4.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions$$anonfun$1(HttpClientBackend.scala:56)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at sttp.monad.MonadError.handleError(MonadError.scala:28)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.SttpClientException$.adjustExceptions(SttpClientException.scala:35)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions(HttpClientBackend.scala:56)
	at sttp.client4.httpclient.HttpClientBackend.send(HttpClientBackend.scala:48)
	at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
	at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1$$anonfun$1(ListenerBackend.scala:18)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1(ListenerBackend.scala:19)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2(ListenerBackend.scala:21)
	at sttp.monad.IdentityMonad$.flatMap(MonadError.scala:178)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send(ListenerBackend.scala:22)
	at sttp.client4.Request.send(request.scala:159)
	at org.CS441.hw3.hdongr2.RestClient$.generate(RestClient.scala:30)
	at org.CS441.hw3.hdongr2.RestClient$.clientLoop(RestClient.scala:42)
	at org.CS441.hw3.hdongr2.RestClient$.runClientLoop(RestClient.scala:50)
	at org.CS441.hw3.hdongr2.runClientLoop.main(RestClient.scala:47)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2043)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1982)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:40)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:38)
	at sttp.client4.httpclient.HttpClientBackend.send$$anonfun$1(HttpClientBackend.scala:47)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	... 38 common frames omitted
Caused by: java.net.ConnectException: null
	at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1065)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	... 3 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:204)
	at java.base/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:873)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:961)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
	at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
	... 9 common frames omitted
16:50:52.894 [sbt-bg-threads-1] WARN  s.c.l.slf4j.Slf4jLoggingBackend - Request: POST http://localhost:8080/query, took: 1.178s, response: 500 , headers: content-length: 5632, content-type: text/plain;charset=utf-8, date: Sat, 30 Nov 2024 22:50:52 GMT, server: Jetty(12.0.10)
16:54:51.071 [sbt-bg-threads-1] WARN  s.c.l.slf4j.Slf4jLoggingBackend - Request: POST http://localhost:8080/query, took: 0.216s, response: 500 , headers: content-length: 6144, content-type: text/plain;charset=utf-8, date: Sat, 30 Nov 2024 22:54:50 GMT, server: Jetty(12.0.10)
20:32:00.236 [sbt-bg-threads-1] ERROR s.c.l.slf4j.Slf4jLoggingBackend - Exception when sending request: POST http://184.73.133.129:8080/query, took: 30.061s
sttp.client4.SttpClientException$TimeoutException: Exception when sending request: POST http://184.73.133.129:8080/query
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException(SttpClientExceptionExtensions.scala:20)
	at sttp.client4.SttpClientExceptionExtensions.defaultExceptionToSttpClientException$(SttpClientExceptionExtensions.scala:8)
	at sttp.client4.SttpClientException$.defaultExceptionToSttpClientException(SttpClientException.scala:24)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions$$anonfun$1(HttpClientBackend.scala:56)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:35)
	at sttp.client4.SttpClientException$$anon$1.applyOrElse(SttpClientException.scala:34)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
	at sttp.monad.MonadError.handleError(MonadError.scala:28)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.SttpClientException$.adjustExceptions(SttpClientException.scala:35)
	at sttp.client4.httpclient.HttpClientBackend.adjustExceptions(HttpClientBackend.scala:56)
	at sttp.client4.httpclient.HttpClientBackend.send(HttpClientBackend.scala:48)
	at sttp.client4.wrappers.FollowRedirectsBackend.sendWithCounter(FollowRedirectsBackend.scala:19)
	at sttp.client4.wrappers.FollowRedirectsBackend.send(FollowRedirectsBackend.scala:15)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1$$anonfun$1(ListenerBackend.scala:18)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	at sttp.monad.MonadError.handleError$(MonadError.scala:18)
	at sttp.monad.IdentityMonad$.handleError(MonadError.scala:175)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2$$anonfun$1(ListenerBackend.scala:19)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send$$anonfun$2(ListenerBackend.scala:21)
	at sttp.monad.IdentityMonad$.flatMap(MonadError.scala:178)
	at sttp.monad.syntax$MonadErrorOps.flatMap(MonadError.scala:63)
	at sttp.client4.listener.ListenerBackend.send(ListenerBackend.scala:22)
	at sttp.client4.Request.send(request.scala:159)
	at org.CS441.hw3.hdongr2.RestClient$.generate(RestClient.scala:26)
	at org.CS441.hw3.hdongr2.RestClient$.clientLoop(RestClient.scala:38)
	at org.CS441.hw3.hdongr2.RestClient$.runClientLoop(RestClient.scala:46)
	at org.CS441.hw3.hdongr2.runClientLoop.main(RestClient.scala:43)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at sbt.Run.invokeMain(Run.scala:144)
	at sbt.Run.execute$1(Run.scala:94)
	at sbt.Run.$anonfun$runWithLoader$5(Run.scala:121)
	at sbt.Run$.executeSuccess(Run.scala:187)
	at sbt.Run.runWithLoader(Run.scala:121)
	at sbt.Defaults$.$anonfun$bgRunTask$6(Defaults.scala:2043)
	at sbt.Defaults$.$anonfun$termWrapper$2(Defaults.scala:1982)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:369)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:950)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:40)
	at sttp.client4.httpclient.HttpClientSyncBackend.sendRegular(HttpClientSyncBackend.scala:38)
	at sttp.client4.httpclient.HttpClientBackend.send$$anonfun$1(HttpClientBackend.scala:47)
	at scala.util.Try$.apply(Try.scala:217)
	at sttp.monad.MonadError.handleError(MonadError.scala:26)
	... 38 common frames omitted
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:620)
	at java.net.http/jdk.internal.net.http.MultiExchange.getExceptionalCF(MultiExchange.java:565)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:485)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Http1Exchange.java:592)
	... 3 common frames omitted
Caused by: java.net.ConnectException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.MultiExchange.toTimeoutException(MultiExchange.java:621)
	... 10 common frames omitted
